### ISSUE TITLE
Computer not sleeping

### ISSUE THREAD

**Issue by Linuus** [cub-uanic/tmk_keyboard#15]
Hi!

When I have my ergodox connected and running this firmware my computer does not go to sleep. The screen turns black for a while and then suddenly it wakes up again.

Is this a known issue?

Apparently others are experiencing the same thing
https://geekhack.org/index.php?topic=48106.msg1244951#msg1244951

**Comment by cub-uanic** [comment]
Already has been fixed in TMK repo and now should be fixed here too.
Please refresh your sources, check, and re-open if needed.
