### ISSUE TITLE
Left hand LEDs usage

### ISSUE THREAD

**Issue by cdarken** [cub-uanic/tmk_keyboard#19]
How can I test if the LEDs are even working? How does the activation of LEDs work depending on the active layer?

Edit: I found the code that should activate the LEDs in matrix.c, I've modified it to count the layers binary using the left hand LEDs but they are not lighting up. They are not lighting up at boot either. How can I debug?

**Comment by squarefrog** [comment]
I suggest you pull in the latest code and try that. The LEDs should light when the keyboard boots. The other thing to check is that your LEDs are placed correctly on the board itself, LEDs are directional so ensure you have them the right way or they wont light.

Pull in the latest code and if it's still not working, open a new issue.
