### ISSUE TITLE
Dvorak Keymap

### ISSUE THREAD

**Issue by Xyverz** [cub-uanic/tmk_keyboard#31]
I've created the attached keymap_dvorak to replace the essentially empty tmk_keyboard-cub_layout/keyboard/ergodox/keymap_dvorak.h.

[keymap_dvorak.h.txt](https://github.com/cub-uanic/tmk_keyboard/files/231045/keymap_dvorak.h.txt)

**Comment by marknsikora** [comment]
Please submit a pull request, and be aware that #29 may cause conflicts in the future

**Comment by cub-uanic** [comment]
Mark, don't you think that if he would familiar with git, he did it from the beginning? :)
I will be thankful if you'll be able to properly handle this file and add it into sources.
If you don't have enough time, I'll take care about this bit later.

**Comment by squarefrog** [comment]
I think this is a great start @Xyverz - I think what would be best would be to make it a little more generic. For example, using Ben Blazeks [qwerty layout](https://github.com/benblazak/ergodox-firmware/blob/master/src/keyboard/ergodox/layout/qwerty-kinesis-mod.c), he has the main layout on layer 0, some functions on layer 1, and a number pad on layer 3. 

I think would could be very useful is creating a generic mapping for each of major layouts, then we can offer pre compiled releases for anyone that just wants to quickly burn the firmware and try it against the stock firmware everyone uses from mass drop. 

Back to @Xyverz, do you feel up to making a pull request for this? Would you like talking through the steps to get something going?

On a side note, this might make a contributing read me file useful for any newcomers..

**Comment by Xyverz** [comment]
@squarefrog - I'm definitely willing to make this a bit more generic. I realize the placement of some of my keys and layers is not very conventional, and can easily make this more common. Any input on setting these layers up would be appreciated.

I would also very much like some help with making a pull request. I've not done it before and the instructions, while they look clear on the surface, I'm still a bit confused by the whole process.

**Comment by olivierpons** [comment]
Hi,

This seems to be about sharing profiles...I'm hope I'm not out of topic,

I've worked some days on a profile which may not be the best, but I've made
an interesting part: a big macro that helps us to have the configuration
easily *readable* by anyone.

Just watch the ERGODOX_KEYMAP()

then you'll see right after how every key map could be written... it's so
practical that maybe more people would want to make their custom
configuration here:

https://github.com/olivierpons/tmk_keyboard/blob/master/keyboard/ergodox/keymap_azerty.h


2016-04-24 2:09 GMT+02:00 Xyverz <notifications@github.com>:

**Comment by marknsikora** [comment]
@olivierpons I like how you've structured your layout to be very readable. Structuring all our layouts like yours in the code would be an improvement in readability. A quick look at your ERGODOX_KEYMAP seems redundant though, it seems like a direct mapping to the existing KEYMAP macro. Is there something I'm missing?

**Comment by marknsikora** [comment]
@Xyverz if you could setup your own pull request that would be great. You can read more about them [here](https://help.github.com/articles/using-pull-requests/). It would be a good learning experience and the changes would be attributed to your github account. Based on @cub-uanic response I realize my closing of this issue may have been a bit premature, and I apologize if that came off a bit strong.

**Comment by olivierpons** [comment]
You're right: it's a mapping to the existing KEYMAP macro. So it should
work right out of the box for all mappings. It's just (IMHO) more readable:
you "visually" see the whole keyboard, and it *might* help other people to
create their own customizations.

2016-04-24 10:30 GMT+02:00 Mark Sikora <notifications@github.com>:

**Comment by marknsikora** [comment]
Haven't heard anything back from @Xyverz in a while. I've finished my cleanup of the layouts (pull #34). If I don't hear anything back before I merge that change I'll close this one myself.

**Comment by Xyverz** [comment]
I apologize, I haven't had the opportunity to do this yet. Due to this delay, please feel free to close this issue. I'll take a closer look at the page you linked and see if I can't figure out how to do a pull request to put in a more generic version of my layout.

**Comment by squarefrog** [comment]
This is merged now
