### ISSUE TITLE
Make with keymap failing - Ergodox FAQ out of date?

### ISSUE THREAD

**Issue by jeffvandyke** [cub-uanic/tmk_keyboard#45]
Running the command `make -f Makefile.lufa dvorak` fails with `make: *** No rule to make target 'dvorak'.  Stop.`.

If `KEYMAP=dvorak make -f Makefile.lufa` is the correct way to do it, then perhaps the Ergodox-FAQ.md file should be updated?

**Comment by SimonLefort** [comment]
Same problem for me...

**Comment by marknsikora** [comment]
Yes correct syntax is

```
make -f Makefile.lufa KEYMAP=dvorak
```

Which docs are you referring to?

**Comment by olivierpons** [comment]
`~ $ cd keyboards/ergodox_infinity/qmk_firmware/
~/keyboards/ergodox_infinity/qmk_firmware $ sudo make ergodox_infinity:azerty:dfu-util MASTER=right`

and then, after I unplug the right, then plug the left:

`~/keyboards/ergodox_infinity/qmk_firmware $ sudo make ergodox_infinity:azerty:dfu-util MASTER=left`

**Comment by marknsikora** [comment]
This is the older tmk firmware that qmk is based off.

I believe you're in the wrong place.

**Comment by rprs** [comment]
Original issue with the instructions is fixed now, so this issue can probably be closed.
