### ISSUE TITLE
Latest Teensy app unable to load hex file.

### ISSUE THREAD

**Issue by andrimarjonsson** [cub-uanic/tmk_keyboard#46]
Tried building my keymap after an update. Builds fine. However when I try to load the built hex file in the Teensy app I get the following error.

> 00:11:33.327: Open File event
00:11:36.781: ihex: parse error line 1454

The tail of my hex reads as follows
> :105AA000A30456042004FE03C503380351036A030C
:0E5AB0008303A303010203040506070809008F
:0200000400807A
:040374000000000085 //<--- complaints about this line. 
:00000001FF

There is one ticket in QMK referring to a similar issue [here](https://github.com/qmk/qmk_firmware/issues/3653). I doubt a similar fix can be applied here since the two makefile setups are different enough at this point.

Any ideas?

**Comment by tmk** [comment]
iirc, one of versions of GCC toolchain caused this problem.
upgrade or downgrade your toolchain.

**Comment by tmk** [comment]
See this also.
https://github.com/tmk/tmk_keyboard/issues/576

**Comment by andrimarjonsson** [comment]
Yes that was it, how did I miss this in my googling.

Thank you very much for a quick and helpful response!

**Comment by marknsikora** [comment]
Yes, I had the same issue. The newest avr tool chain on arch seems to be working again though. 

I'm going to close this for now.
