### ISSUE TITLE
Issues after pressing SW3:9 and SW4:7 simultaneously in debug & matrix mode.

### ISSUE THREAD

**Issue by morinted** [cub-uanic/tmk_keyboard#7]
When in debug & matrix mode (Shift_L+Shift_R+D, Shift_L+Shift_R+X), if SW3:9 and SW4:7 are pressed simultaneously, keyboard starts behaving erroneously.

**Comment by squarefrog** [comment]
Is this still an issue?

**Comment by morinted** [comment]
I believe it was a hardware fault.
